server:
  port: 9411

spring:
  application:
    name: zipkin
    
eureka:
  client:
#    register-with-eureka: true
#    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
#
#management:
#  security:
#    enabled: false


      
      
    