package com.xinmao.common.userOperationCenter.mapper;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.github.pagehelper.Page;
import com.xinmao.common.userCenter.domain.Member;

public interface MemberMapper {
	
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbggenerated  Wed May 30 14:33:41 CST 2018
	 */
	int insertSelective(Member record);

	
}
