package com.xinmao.common.userOperationCenter.mapper;

import java.util.List;

//import com.depression.model.CapitalIncomeExpenses;
//import com.depression.model.ServiceOrder;
import com.xinmao.common.userOperationCenter.domain.ServiceOrder;

public interface ServiceOrderMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_order
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	List<ServiceOrder> selectSelective(ServiceOrder record);
	
}
