package com.xinmao.common.userOperationCenter.mapper;

//import com.depression.model.ServiceCallRecord;
import java.util.List;

import com.xinmao.common.userOperationCenter.domain.ServiceCallRecord;

public interface ServiceCallRecordMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table service_call_record
	 * @mbggenerated  Thu Jun 08 17:22:13 CST 2017
	 */
	List<ServiceCallRecord> selectSelective(ServiceCallRecord record);

}
