server:
  port: 9000
#  ssl:
#    key-store: classpath:api.120xinmao.com.jks
#    key-store-password: xinmao
#    key-store-type: JKS
#    key-alias: xinmao
    
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 60000

spring:
  application:
    name: zuul
  datasource:
#    url: jdbc:mysql://192.168.0.247:3306/test_depression?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
#    username: root
#    password: root
    url: jdbc:mysql://127.0.0.1:3306/depression?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 
    driver-class-name: com.mysql.jdbc.Driver
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
    
    
#数据库连接配置
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mappers/*.xml
    
#port:
#  springClound: 8000
#  depression: 8080

    
eureka:
  client:
    service-url:
#      defaultZone: http://192.168.0.193:8001/eureka/
      defaultZone: http://localhost:8001/eureka/

management:
  security:
    enabled: false

zuul:
  retryable: true
  #ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
    
#  routes:
#    testCenter-provider:
#         path: /testCenter/**
#         url: http://api.120xinmao.com:8000/
#         stripPrefix: false
#         sensitiveHeaders: 
#    eap:
#        path: /depression-eap/**
#        url: http://localhost:8080/
#        stripPrefix: false
#        sensitiveHeaders:

#    api:
#        path: /depression-api/**
#        url: http://localhost:8080/
#        stripPrefix: false
#        sensitiveHeaders:

#    web:
#        path: /depression-web/**
#        url: http://localhost:8080/
#        stripPrefix: false
#        sensitiveHeaders:  
        
#    testCenter-provider:
#        path: /testCenter/**
#        serviceId: testCenter-provider

#    orderCenter-provider:
#        path: /orderCenter/**
        
        
logging:
  config: classpath:log4j2-local.xml
  




      
      
    