package com.xinmao.common.userOperationCenter.domain;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import com.xinmao.common.entity.Page;

public class ServiceOrder extends Page {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_order.soid
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	private Long soid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_order.ssid
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	private Long ssid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_order.sgid
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	private Long sgid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_order.mid
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	private Long mid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_order.service_provider_id
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	private Long serviceProviderId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_order.no
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	private String no;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_order.create_time
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_order.service_begin_time
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	private Date serviceBeginTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_order.service_reality_begin_time
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	private Date serviceRealityBeginTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_order.goods_quantity
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	private Integer goodsQuantity;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_order.cost
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	private BigDecimal cost;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_order.practical_duration
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	private Integer practicalDuration;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_order.dbid
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	private Long dbid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_order.discount_amount
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	private BigDecimal discountAmount;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_order.commission_rate
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	private Integer commissionRate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_order.cash_amount
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	private BigDecimal cashAmount;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_order.status
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	private Byte status;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_order.refund_status
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	private Byte refundStatus;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_order.refund_platform_amount
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	private BigDecimal refundPlatformAmount;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_order.refund_server_amount
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	private BigDecimal refundServerAmount;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_order.order_type
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	private Byte orderType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_order.ee_id
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	private Long eeId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_order.operator
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	private String operator;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_order.operation_log
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	private String operationLog;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_order.remarks
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	private String remarks;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_order.consult_content
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	private String consultContent;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_order.consult_name
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	private String consultName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_order.consult_sex
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	private Byte consultSex;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_order.consult_age
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	private Integer consultAge;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_order.consult_phone
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	private String consultPhone;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_order.consult_profession
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	private String consultProfession;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_order.invisible_user
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	private Byte invisibleUser;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_order.invisible_psycho
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	private Byte invisiblePsycho;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_order.is_recommend
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	private Byte isRecommend;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_order.recommand_price
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	private BigDecimal recommandPrice;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_order.is_enable
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	private Byte isEnable;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_order.is_delete
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	private Byte isDelete;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_order.notestatus
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	private Byte notestatus;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_order.price
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	private BigDecimal price;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_order.duration
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	private Integer duration;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_order.order_source
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	private Byte orderSource;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_order.apid
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	private Long apid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_order.finish_time
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	private Date finishTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_order.is_new_app
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	private Byte isNewApp;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_order.noid
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	private Long noid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_order.psycho_status
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	private Byte psychoStatus;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_order.comsumer_status
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	private Byte comsumerStatus;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_order.caid
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	private Long caid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column service_order.parent_order_id
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	private Long parentOrderId;


	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_order.soid
	 * @return  the value of service_order.soid
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public Long getSoid() {
		return soid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_order.soid
	 * @param soid  the value for service_order.soid
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public void setSoid(Long soid) {
		this.soid = soid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_order.ssid
	 * @return  the value of service_order.ssid
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public Long getSsid() {
		return ssid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_order.ssid
	 * @param ssid  the value for service_order.ssid
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public void setSsid(Long ssid) {
		this.ssid = ssid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_order.sgid
	 * @return  the value of service_order.sgid
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public Long getSgid() {
		return sgid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_order.sgid
	 * @param sgid  the value for service_order.sgid
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public void setSgid(Long sgid) {
		this.sgid = sgid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_order.mid
	 * @return  the value of service_order.mid
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public Long getMid() {
		return mid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_order.mid
	 * @param mid  the value for service_order.mid
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public void setMid(Long mid) {
		this.mid = mid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_order.service_provider_id
	 * @return  the value of service_order.service_provider_id
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public Long getServiceProviderId() {
		return serviceProviderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_order.service_provider_id
	 * @param serviceProviderId  the value for service_order.service_provider_id
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public void setServiceProviderId(Long serviceProviderId) {
		this.serviceProviderId = serviceProviderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_order.no
	 * @return  the value of service_order.no
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public String getNo() {
		return no;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_order.no
	 * @param no  the value for service_order.no
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public void setNo(String no) {
		this.no = no == null ? null : no.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_order.create_time
	 * @return  the value of service_order.create_time
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_order.create_time
	 * @param createTime  the value for service_order.create_time
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_order.service_begin_time
	 * @return  the value of service_order.service_begin_time
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public Date getServiceBeginTime() {
		return serviceBeginTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_order.service_begin_time
	 * @param serviceBeginTime  the value for service_order.service_begin_time
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public void setServiceBeginTime(Date serviceBeginTime) {
		this.serviceBeginTime = serviceBeginTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_order.service_reality_begin_time
	 * @return  the value of service_order.service_reality_begin_time
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public Date getServiceRealityBeginTime() {
		return serviceRealityBeginTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_order.service_reality_begin_time
	 * @param serviceRealityBeginTime  the value for service_order.service_reality_begin_time
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public void setServiceRealityBeginTime(Date serviceRealityBeginTime) {
		this.serviceRealityBeginTime = serviceRealityBeginTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_order.goods_quantity
	 * @return  the value of service_order.goods_quantity
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public Integer getGoodsQuantity() {
		return goodsQuantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_order.goods_quantity
	 * @param goodsQuantity  the value for service_order.goods_quantity
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public void setGoodsQuantity(Integer goodsQuantity) {
		this.goodsQuantity = goodsQuantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_order.cost
	 * @return  the value of service_order.cost
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public BigDecimal getCost() {
		return cost;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_order.cost
	 * @param cost  the value for service_order.cost
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public void setCost(BigDecimal cost) {
		this.cost = cost;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_order.practical_duration
	 * @return  the value of service_order.practical_duration
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public Integer getPracticalDuration() {
		return practicalDuration;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_order.practical_duration
	 * @param practicalDuration  the value for service_order.practical_duration
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public void setPracticalDuration(Integer practicalDuration) {
		this.practicalDuration = practicalDuration;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_order.dbid
	 * @return  the value of service_order.dbid
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public Long getDbid() {
		return dbid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_order.dbid
	 * @param dbid  the value for service_order.dbid
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public void setDbid(Long dbid) {
		this.dbid = dbid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_order.discount_amount
	 * @return  the value of service_order.discount_amount
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public BigDecimal getDiscountAmount() {
		return discountAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_order.discount_amount
	 * @param discountAmount  the value for service_order.discount_amount
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public void setDiscountAmount(BigDecimal discountAmount) {
		this.discountAmount = discountAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_order.commission_rate
	 * @return  the value of service_order.commission_rate
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public Integer getCommissionRate() {
		return commissionRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_order.commission_rate
	 * @param commissionRate  the value for service_order.commission_rate
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public void setCommissionRate(Integer commissionRate) {
		this.commissionRate = commissionRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_order.cash_amount
	 * @return  the value of service_order.cash_amount
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public BigDecimal getCashAmount() {
		return cashAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_order.cash_amount
	 * @param cashAmount  the value for service_order.cash_amount
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public void setCashAmount(BigDecimal cashAmount) {
		this.cashAmount = cashAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_order.status
	 * @return  the value of service_order.status
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_order.status
	 * @param status  the value for service_order.status
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_order.refund_status
	 * @return  the value of service_order.refund_status
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public Byte getRefundStatus() {
		return refundStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_order.refund_status
	 * @param refundStatus  the value for service_order.refund_status
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public void setRefundStatus(Byte refundStatus) {
		this.refundStatus = refundStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_order.refund_platform_amount
	 * @return  the value of service_order.refund_platform_amount
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public BigDecimal getRefundPlatformAmount() {
		return refundPlatformAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_order.refund_platform_amount
	 * @param refundPlatformAmount  the value for service_order.refund_platform_amount
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public void setRefundPlatformAmount(BigDecimal refundPlatformAmount) {
		this.refundPlatformAmount = refundPlatformAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_order.refund_server_amount
	 * @return  the value of service_order.refund_server_amount
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public BigDecimal getRefundServerAmount() {
		return refundServerAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_order.refund_server_amount
	 * @param refundServerAmount  the value for service_order.refund_server_amount
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public void setRefundServerAmount(BigDecimal refundServerAmount) {
		this.refundServerAmount = refundServerAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_order.order_type
	 * @return  the value of service_order.order_type
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public Byte getOrderType() {
		return orderType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_order.order_type
	 * @param orderType  the value for service_order.order_type
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public void setOrderType(Byte orderType) {
		this.orderType = orderType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_order.ee_id
	 * @return  the value of service_order.ee_id
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public Long getEeId() {
		return eeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_order.ee_id
	 * @param eeId  the value for service_order.ee_id
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public void setEeId(Long eeId) {
		this.eeId = eeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_order.operator
	 * @return  the value of service_order.operator
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public String getOperator() {
		return operator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_order.operator
	 * @param operator  the value for service_order.operator
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public void setOperator(String operator) {
		this.operator = operator == null ? null : operator.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_order.operation_log
	 * @return  the value of service_order.operation_log
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public String getOperationLog() {
		return operationLog;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_order.operation_log
	 * @param operationLog  the value for service_order.operation_log
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public void setOperationLog(String operationLog) {
		this.operationLog = operationLog == null ? null : operationLog.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_order.remarks
	 * @return  the value of service_order.remarks
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public String getRemarks() {
		return remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_order.remarks
	 * @param remarks  the value for service_order.remarks
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks == null ? null : remarks.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_order.consult_content
	 * @return  the value of service_order.consult_content
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public String getConsultContent() {
		return consultContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_order.consult_content
	 * @param consultContent  the value for service_order.consult_content
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public void setConsultContent(String consultContent) {
		this.consultContent = consultContent == null ? null : consultContent
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_order.consult_name
	 * @return  the value of service_order.consult_name
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public String getConsultName() {
		return consultName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_order.consult_name
	 * @param consultName  the value for service_order.consult_name
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public void setConsultName(String consultName) {
		this.consultName = consultName == null ? null : consultName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_order.consult_sex
	 * @return  the value of service_order.consult_sex
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public Byte getConsultSex() {
		return consultSex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_order.consult_sex
	 * @param consultSex  the value for service_order.consult_sex
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public void setConsultSex(Byte consultSex) {
		this.consultSex = consultSex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_order.consult_age
	 * @return  the value of service_order.consult_age
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public Integer getConsultAge() {
		return consultAge;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_order.consult_age
	 * @param consultAge  the value for service_order.consult_age
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public void setConsultAge(Integer consultAge) {
		this.consultAge = consultAge;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_order.consult_phone
	 * @return  the value of service_order.consult_phone
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public String getConsultPhone() {
		return consultPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_order.consult_phone
	 * @param consultPhone  the value for service_order.consult_phone
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public void setConsultPhone(String consultPhone) {
		this.consultPhone = consultPhone == null ? null : consultPhone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_order.consult_profession
	 * @return  the value of service_order.consult_profession
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public String getConsultProfession() {
		return consultProfession;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_order.consult_profession
	 * @param consultProfession  the value for service_order.consult_profession
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public void setConsultProfession(String consultProfession) {
		this.consultProfession = consultProfession == null ? null
				: consultProfession.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_order.invisible_user
	 * @return  the value of service_order.invisible_user
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public Byte getInvisibleUser() {
		return invisibleUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_order.invisible_user
	 * @param invisibleUser  the value for service_order.invisible_user
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public void setInvisibleUser(Byte invisibleUser) {
		this.invisibleUser = invisibleUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_order.invisible_psycho
	 * @return  the value of service_order.invisible_psycho
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public Byte getInvisiblePsycho() {
		return invisiblePsycho;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_order.invisible_psycho
	 * @param invisiblePsycho  the value for service_order.invisible_psycho
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public void setInvisiblePsycho(Byte invisiblePsycho) {
		this.invisiblePsycho = invisiblePsycho;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_order.is_recommend
	 * @return  the value of service_order.is_recommend
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public Byte getIsRecommend() {
		return isRecommend;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_order.is_recommend
	 * @param isRecommend  the value for service_order.is_recommend
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public void setIsRecommend(Byte isRecommend) {
		this.isRecommend = isRecommend;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_order.recommand_price
	 * @return  the value of service_order.recommand_price
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public BigDecimal getRecommandPrice() {
		return recommandPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_order.recommand_price
	 * @param recommandPrice  the value for service_order.recommand_price
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public void setRecommandPrice(BigDecimal recommandPrice) {
		this.recommandPrice = recommandPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_order.is_enable
	 * @return  the value of service_order.is_enable
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public Byte getIsEnable() {
		return isEnable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_order.is_enable
	 * @param isEnable  the value for service_order.is_enable
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public void setIsEnable(Byte isEnable) {
		this.isEnable = isEnable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_order.is_delete
	 * @return  the value of service_order.is_delete
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public Byte getIsDelete() {
		return isDelete;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_order.is_delete
	 * @param isDelete  the value for service_order.is_delete
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public void setIsDelete(Byte isDelete) {
		this.isDelete = isDelete;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_order.notestatus
	 * @return  the value of service_order.notestatus
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public Byte getNotestatus() {
		return notestatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_order.notestatus
	 * @param notestatus  the value for service_order.notestatus
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public void setNotestatus(Byte notestatus) {
		this.notestatus = notestatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_order.price
	 * @return  the value of service_order.price
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public BigDecimal getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_order.price
	 * @param price  the value for service_order.price
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_order.duration
	 * @return  the value of service_order.duration
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public Integer getDuration() {
		return duration;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_order.duration
	 * @param duration  the value for service_order.duration
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public void setDuration(Integer duration) {
		this.duration = duration;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_order.order_source
	 * @return  the value of service_order.order_source
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public Byte getOrderSource() {
		return orderSource;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_order.order_source
	 * @param orderSource  the value for service_order.order_source
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public void setOrderSource(Byte orderSource) {
		this.orderSource = orderSource;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_order.apid
	 * @return  the value of service_order.apid
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public Long getApid() {
		return apid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_order.apid
	 * @param apid  the value for service_order.apid
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public void setApid(Long apid) {
		this.apid = apid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_order.finish_time
	 * @return  the value of service_order.finish_time
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public Date getFinishTime() {
		return finishTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_order.finish_time
	 * @param finishTime  the value for service_order.finish_time
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public void setFinishTime(Date finishTime) {
		this.finishTime = finishTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_order.is_new_app
	 * @return  the value of service_order.is_new_app
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public Byte getIsNewApp() {
		return isNewApp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_order.is_new_app
	 * @param isNewApp  the value for service_order.is_new_app
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public void setIsNewApp(Byte isNewApp) {
		this.isNewApp = isNewApp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_order.noid
	 * @return  the value of service_order.noid
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public Long getNoid() {
		return noid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_order.noid
	 * @param noid  the value for service_order.noid
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public void setNoid(Long noid) {
		this.noid = noid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_order.psycho_status
	 * @return  the value of service_order.psycho_status
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public Byte getPsychoStatus() {
		return psychoStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_order.psycho_status
	 * @param psychoStatus  the value for service_order.psycho_status
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public void setPsychoStatus(Byte psychoStatus) {
		this.psychoStatus = psychoStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_order.comsumer_status
	 * @return  the value of service_order.comsumer_status
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public Byte getComsumerStatus() {
		return comsumerStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_order.comsumer_status
	 * @param comsumerStatus  the value for service_order.comsumer_status
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public void setComsumerStatus(Byte comsumerStatus) {
		this.comsumerStatus = comsumerStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_order.caid
	 * @return  the value of service_order.caid
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public Long getCaid() {
		return caid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_order.caid
	 * @param caid  the value for service_order.caid
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public void setCaid(Long caid) {
		this.caid = caid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column service_order.parent_order_id
	 * @return  the value of service_order.parent_order_id
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public Long getParentOrderId() {
		return parentOrderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column service_order.parent_order_id
	 * @param parentOrderId  the value for service_order.parent_order_id
	 * @mbggenerated  Wed Jun 13 15:52:34 CST 2018
	 */
	public void setParentOrderId(Long parentOrderId) {
		this.parentOrderId = parentOrderId;
	}

	private List<Byte> statusList;
	
	private Date createTimeStart;
	
	private Date createTimeEnd;
	

	public List<Byte> getStatusList() {
		return statusList;
	}

	public void setStatusList(List<Byte> statusList) {
		this.statusList = statusList;
	}

	public Date getCreateTimeStart() {
		return createTimeStart;
	}

	public void setCreateTimeStart(Date createTimeStart) {
		this.createTimeStart = createTimeStart;
	}

	public Date getCreateTimeEnd() {
		return createTimeEnd;
	}

	public void setCreateTimeEnd(Date createTimeEnd) {
		this.createTimeEnd = createTimeEnd;
	}
}