server:
  port: 8001

spring:
  application:
    name: EurekaServer
    

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://es1:8001/eureka/
  instance:
    #prefer-ip-address: true
    instance-id:  ${spring.cloud.client.ipAddress}:${server.port}
    hostname: es1  